# Generated by Django 5.0.2 on 2024-03-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='cleanliness',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='feelings',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='food',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='politeness',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='recommend',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
