# Generated by Django 5.0.2 on 2024-03-03 06:53

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0002_alter_survey_cleanliness_alter_survey_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
