# Generated by Django 5.0.3 on 2024-06-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0003_alter_survey_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='recommend',
            field=models.IntegerField(null=True),
        ),
    ]
