# Generated by Django 5.0.3 on 2024-06-10 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0005_secondlocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecondLocation',
        ),
    ]
