# Generated by Django 5.0.3 on 2024-06-11 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0007_survey_b'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey_b',
            old_name='food',
            new_name='vent',
        ),
    ]
